apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fast-api-servicemonitor
  namespace: fast-api
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: fast-api-application
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
