name: CI-CD

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python Environment
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: format code
        run: black --check .
      - name: lint code
        run: ruff check . --select I
      - name: test with pytest
        run: pytest -v


