name: CI-CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
  
    permissions:
      contents: write
      packages: write
    
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "password123"
          POSTGRES_DB: "tasksdb"
        ports:
          - 5432:5432
        options: >- 
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install -r requirements.txt
      
      - name: Check Code Formatting
        run: black --check .
      
      - name: Lint Code
        run: ruff check . --select I

      - name: Test with Pytest
        env:
          APP_NAME: "Task Awesome"
          APP_VERSION: "3.0.0"
          ENVIRONMENT: "developmentisago!"
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pytest -v app/

      - name: Login, Build and Push to Docker Hub
        run: |
          docker build -t prospjx/imain-app:latest -f docker/Dockerfile .
          docker login -u prospjx -p ${{ secrets.DOCKER_PATCODE }}
          docker push prospjx/imain-app:latest
      
      - name: Build, Login and Push to GHCR
        run: |
          IMAGE_ID = ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')/imain-app:latest
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username {{ github.actor }} --password-stdin
          docker build -t $IMAGE_ID -f docker/Dockerfile .
          docker push $IMAGE_ID
      

    